### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi ! I noticed there was a few issues with Pho. I made some changes. Here is the full changelog:

# Changelog
- [X] Fix appdata translations
- [X] Split translations between extra (appdata, desktop) translations and main translations
- [X] Remove empty translation files
- [X] Add version number to `meson.build`
- [X] Add `post_install.py` script to make sure that schema are compiled and update icon cache
- [X] Add some tooltips to buttons and to loading spinner
- [X] Add missing translations
- [X] Update French translations

I built the app and this is working well! :smile: Let me know if you have any questions.

**This PR is ready for review**

### CODE REVIEW

**Comment by NathanBnm** [comment]
Idk why the build is falling. Do you have any idea? Apparently it can't find the `meson/post_instal.py` script but this is strange 'cause I linked it correctly and it's working when I build locally. There must be some issue with deb packaging. I'm note sure about it.

**Comment by NathanBnm** [comment]
@dcharles525 Apparently debian rules are making the build falling, I don't really know, I tried removing them on another app and this is working again.

**Comment by dcharles525** [comment]
@NathanBnm Thanks for all the work! I am going to merge this in and take a look on my end.

**Comment by NathanBnm** [comment]
@dcharles525 you may have to make the `post_install.py` script executable with the following command as reported here https://github.com/artemanufrij/playmymusic/pull/172#issuecomment-485243829

**Pull request merged**
